[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tokio-serial = "5.4.5"
tokio-util = "0.7.18"
thiserror = { workspace = true }
smallvec = { workspace = true }
async-trait = { workspace = true }
